export * from './BoletaCreate';
export * from './BoletaDetail';
export * from './BoletasList';
export * from './BoletaUpdate';
export * from './Inicio';
export * from './Login';
export * from './MisBoletas';
export * from './NotFound';
export * from './ScannerQR';